### PR TITLE
Typescript definitions

### PR DESCRIPTION
**Pull request by Windrill**

### CODE REVIEW

**Comment by mrdoob** [comment]
Isn't the extension supposed to be `.d.ts`?

**Comment by mrdoob** [comment]
Oh wait, that's not a definitions file. That's the same code in TypeScript, no?

**Comment by Windrill** [comment]
Yes, wanted to add the type definitions for TS projects, where the usage would be the same with types. You wanted to use it as a module too?

**Comment by mrdoob** [comment]
As far as I understand, what you're trying to contribute is the typescript version of the library.

This is how a definitions file look like:
https://github.com/three-types/three-ts-types/blob/master/types/three/src/core/Object3D.d.ts

**Comment by Windrill** [comment]
That made a lot of sense, thanks. Updated with the definitions file.

**Comment by mrdoob** [comment]
Thanks!

**Pull request merged**
